on:
  push:
    branches:
      - src
  pull_request:
    branches:
      - src

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:

    - name: Check out
      uses: actions/checkout@v2
    
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'Makesphere'
        email: 'makeshasphere@gmail.com'
        actor: 'Makesphere'
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install
      run:  |
        pip install -U pip
        pip install poetry
        poetry install --no-root -v

    - name: Build
      run:  |
        nikola build

    - name: Deploy
      run:  |
        nikola github_deploy